version: '3.9'

services:
  plantnet-app:
    build:
      context: .
      dockerfile: frontend/Dockerfile
    ports:
      - "8501:8501"
    volumes:
      - ./frontend:/app
    environment:
      - API_KEY=BuWptEWokk2rDa04HvCSLyWupnE5hiRYV5QFuajtVaNWMi2YkC  
